### ISSUE TITLE
Model 475 Pur Cool Link; no fan controls other than off/om switch

### ISSUE THREAD

**Issue by nx2i** [shenxn/ha-dyson#104]
Thanks for this integration! Forgive me if this has been discussed previously. I have a Pure Cool Link (model 475) that I have integrated into HA using the manual procedure described in the README file. The code self discovers 9 entities; most are sensors, and there are 3 switches. These entities are:
fan.pure_cool_link, switch.pure_cool_link_continuous_monitoring, and switch.pure_cool_link_night_mode. Only the fan on/off appears as a control. There are no entities or associated controls for fan speed and oscillation. How do I get these controls added for both the 2 entities listed above and the missing fan speed and oscilllation?

**Comment by nx2i** [comment]
to clarify, I have the controls for night mode and continuous monitoring working. Where are controls for fan speed and oscillation?

**Comment by DarkC35** [comment]
Hi, I ran into this "problem" myself (because it was my first time using a fan im HA) and found the discussion here https://github.com/shenxn/ha-dyson/issues/75#issuecomment-991919715

The short answer: These two controls you are missing are placed directly at the fan control element. This is the intended behavior by HA. Controls that you can use in the UI can be made with the fan scripts: https://www.home-assistant.io/integrations/fan/
