### ISSUE TITLE
Failure adding integration

### ISSUE THREAD

**Issue by dazzlindazdance** [shenxn/ha-dyson#106]
Hi

I am running core and have ha-dyson added as a custom component, I attempt to add the Dyson Local integration and i am met with the following error message and cannot proceed:

"Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant."

Any ideas on what this or when it will be remediated?  What do you need from me to diagnose?

Thanks
Darren

**Comment by ghostsam45** [comment]
same issue

**Comment by xyzsesame** [comment]
Try with the test version.

**Comment by Gtwizzy** [comment]
Same issue

**Comment by Gtwizzy** [comment]
@xyzsesame Could you possibly explain how to attempt the install of the test version?

**Comment by Kakise** [comment]
Fixed in last update, 0.16.3

**Comment by SchallerJe** [comment]
This problem seems to be back again with v0.16.4-4 and Home Assistant 2022.7.5. Neither cloud nor local can be set up.

Error message in Home Assistant:
"Error occurred loading configuration flow for integration dyson_cloud: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.10/site-packages/libdyson/__init__.py)"

**Comment by Rathvire** [comment]
Can second this is back. Both Dyson Local and Dyson Cloud give me the error, versions below.

Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

**Comment by slyoldfox** [comment]
@Kakise can you revisit this? I checked if dyson cloud was working again but it does not seem to work either with dyson-local 0.16.4-4

**Comment by snigehere** [comment]
I had to remove both dyson local and dyson cloud integrations completely from my system (both in the integration and hacs).  I then re-started the whole system.  Once done I as able to successfully add back dyson cloud, did do the setup (ensuring I signed off of my app first).  Once setup I was then able to add dyson local and removed cloud and it then worked fine.  Having removed the dyson cloud integration I was then able to log back onto my phone app so now I can control from both.

**Comment by slyoldfox** [comment]
I understand. I had a correctly setup dyson local as well (manual setup). But the environmental data would just stop refreshing after a few hours. 
I tried all procedures several times now. I was revisiting Dyson Cloud. 

I removed some lines concerning the DysonPurifierHumidifyCoolFormaldehyde error from `custom_components/dyson_local/__init__.py`.

I was presented by a GUI flow however when entering my email I receive a "Failed to connect" error.
So well dyson local doesn't work because the environment statistics drop out after a few hours.

Dyson cloud is just not configurable.

**Comment by Baricang** [comment]
Hi guys, 

i have the same issue with my dyson cloud. 
I have installed dyson cload 0.14 (and i tried 0.15 also). 
After adding under devices "dyson cloud" an error. "Error configurationflow could not be loaded..." 

I also tried Dyson Local... same issue. 
Do someone has an idea what i can try next?

![Screenshot 2022-11-13 14 26 14](https://user-images.githubusercontent.com/55063915/201524160-55698146-8950-465c-9746-40ce443661c5.png)

**Comment by shadyabhi** [comment]
>I also tried Dyson Local... same issue.

@Baricang 

There's something wrong with Dyson Cloud, didn't spend time to debug further. However, I suspect it as something to do with libdyson version, which is outdated for Dyson Cloud. https://github.com/shenxn/ha-dyson/issues/173#issuecomment-1365819366

In my case, if I uninstall `Dyson Cloud`, the error in `Dyson Local` goes away too.

**Comment by tinybighuman** [comment]
I've had the same issue today with Dyson Cloud. It doesn't work anymore with the error `Config flow could not be loaded: {"message":"Invalid handler specified"}`

**Comment by Vatoe** [comment]
Same here Error occurred loading configuration flow for integration dyson_cloud: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.10/site-packages/libdyson/__init__.py)

**Comment by Baricang** [comment]
Get it working but now i got the same error as Vatoe everytime i restart HA. 
Means that i got it working but with each restart the integration is not working anymore. 
And the best... now im not even able to uninstall it.
