### ISSUE TITLE
Dyson Local and Cloud not loading on 2022.5.3

### ISSUE THREAD

**Issue by karanbhargava** [shenxn/ha-dyson#136]
I recently upgraded from 2022.5.2 to 2022.5.3 and have been unable to load the local and cloud integrations

Here is the relevant log output 
![049CA4D7-AC93-4D19-B590-D06ECA6FB78D](https://user-images.githubusercontent.com/23252781/167538464-1acefebe-1b03-4b99-a113-7f7f702de634.png)

Any help or guidance is appreciated.

**Comment by karanvivekbhargava** [comment]
Since the custom integrations don’t get loaded, the connected devices are showing as unavailable.

**Comment by Kakise** [comment]
The issue you are encountering is because of two conflicting versions of libdyson. dyson-cloud is not maintained anymore and thus, does not work at all, and installs an old version of libdyson, which conflicts with the one required by dyson-local.

What you should to return to a usable state is:
- Uninstall both dyson-cloud and dyson-local
- Run `pip uninstall -y libdyson`
- Install only dyson-local

**Comment by karanvivekbhargava** [comment]
Just putting some things here in case someone gets stuck
You'd have to just remove dyson-cloud via integrations. But still do what @Kakise pointed out earlier if this doesn't work.
** Disable dyson-cloud and dyson-local first in the integrations (not in HACS)
** Restart Home Assistant
** Remove dyson-cloud
** Restart Home Assistant
** Enable dyson-local
** Restart Home Assistant
Had to use this roundabout approach since the integration wasn't getting removed when using the remove command directly.

**Comment by karanvivekbhargava** [comment]
Thanks @Kakise for the help! :)

**Comment by Kakise** [comment]
> Thanks @Kakise for the help! :)

Glad to hear it works ! :D
