### ISSUE TITLE
Pure Cool Link - becomes unavailable sporadically

### ISSUE THREAD

**Issue by Anto79-ops** [shenxn/ha-dyson#142]
Hi,

thanks again for making the integration happen. I have 6 Dyson fans connected to this integration, but there is one machine that acts differently then the rest. 2 of my machines are Pure Cool Link machines, but one of them, often becomes unavailable, and sometimes comes back to report to HA. The other Pure Cool Link is rock solid (like the other fans) and stay online all the time. I've often had to delete the one fan, and re-add it again, only to become unavailable again, at some point. Its 10 ft away from my internet access point, so I don't think its related to WiFi connectivity but who knows. 

Any idea why this particular machine mis-behaves and becomes unavailable? I've added this machine both way (Via the Wifi credentials AND the manual credentials). When its unavailable in HA I can still access the machine using the Dyson app.

Here's an example of the temperature history, and you can see how often it becomes unavailable to available (but sometimes it just stays unavailable until I delete and readd).

![plotDYSON](https://user-images.githubusercontent.com/79593761/172751559-e71cf067-e63b-4222-b557-2a160c4b167b.jpg)

**Comment by BCorbeek** [comment]
Having same issue with Pure Hot+Cool the last few days. Has been working perfectly up until now - any ideas on what the cause is are welcome (maybe something changed recently on Dyson's end?). And thanks a ton for this integration - really love it!

tip: restarting home assistant does reconnect the dyson - but that's not something you want to repeat very often

![image](https://user-images.githubusercontent.com/30185871/173805447-8c23ac54-6268-447d-8866-7623e2b1f09b.png)

**Comment by Anto79-ops** [comment]
thanks for sharing. Just curious, how does the reconnect work? i.e. does it try every 10 minutes or so? How can you force a reconnect without restarting HA? thanks

In all fairness to the integration, even the dyson app somestimes does not connect on the first try, but when I press refresh it does. Perhaps a refresh option can be implemented?

**Comment by jax-tr** [comment]
I have the same issue. Dyson Pure Hot+Cool becomes unavailable after a while and I haven't found any way to make it work again unless I delete and reconfigure the integration...

**Comment by jstott1070** [comment]
Ditto - Hot & Cool unavailable, has been pretty stable until a week or so again (I think)

**Comment by Anto79-ops** [comment]
I recently changed my router and the connection to my Dyson fans have been almost perfect.

In about a month with my new router there was one fan that became unavailable and I unplugged it and plugged it back in and it became instantly available in HA.

I suspect the connection issues I was experiencing was related to how my old router was handling too many devices on my home wifi, 84 to be exact.

Being the op of this thread I can consider this solved in closed but I won't close it as many of your comments could be related to something else, if it's not Wi-Fi connection issues.

**Comment by erd82** [comment]
I have the same problem with my Dyson Purifier Cool Formaldehyde (TP09) that the integration suddenly becomes unavailable.

My experience:
1. I tried to restart Home Assistant which did not work. 
2. Then I logged of from the Dyson Link mobile app.
3. After restarting again, the Dyson integration worked again.

With the "Unknown Error Occurred" issue (https://github.com/shenxn/ha-dyson/issues/99) we learned that you have to log out from the mobile app in order to register your Dyson Cloud in Home Assistant.

Conclusion: Could it be that Dyson allows only one connection / device at the same time? As soon as you have connected with home assistant and your Dyson Link mobile app at the same time, one connection (probably not Dyson Link) will fail.

Do you agree? Can anyone confirm?
