### ISSUE TITLE
Update - Dyson purifier cool (2021)

### ISSUE THREAD

**Issue by DeXter3306** [shenxn/ha-dyson#38]
I just bought the Dyson Purifier Cool (2021) and apparently the MQTT Topic has been updated also.

Instead of :
438/\<DEVICE SERIAL\>/status/current 
it is now : 
438E/\<DEVICE SERIAL\>/status/current

Would it be possible to update the device list with the new Purifier Cool (2021)
https://www.dyson.be/fr_be/traitement-de-l-air/purificateurs/dyson-pure-cool/dyson-purifier-cool-blanc-argent

Thanks !

**Comment by shenxn** [comment]
Done. Please try update and re-add your device.

**Comment by DeXter3306** [comment]
It works ! Thanks mate !

**Comment by erd82** [comment]
@shenxn 

I also have the **[Dyson Purifier Cool (438E)](https://www.dyson.co.uk/content/dam/dyson/maintenance/user-guides/en_GB/airtreatment/Purifiers/TP07/TP%20Owner%20Manual.pdf)**, which I is not offered in the device type list:
![image](https://user-images.githubusercontent.com/63564291/150857278-541883c3-c900-459e-bcc3-1fe12a81cf10.png)

Until today, Dyson Local integration offered "_Pure Cool (2021)_", which worked to me in order to added the device to Home Assistant. After removing it and trying again, suddenly the types "_Pure Cool Formaldehyde_" appeared, which also worked to add my device.

Finally the **name is not the right one**, but would you say that should be fine?

I am asking, because I used Dyson Cloud in the past and there I could switch the **Auto Mode**. This is not possible anymore today. Should I open another issue for the Auto Mode?

![image](https://user-images.githubusercontent.com/63564291/150860485-caf2ee73-3789-49a9-96be-d2b64d0e60d1.png)
