### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by fabltd** [shenxn/ha-dyson#66]
Attempting to setup Dyson Cloud 

Region UK ( GB) 

Enter email address and get the error - Failed to connect.

**Comment by smallbitt** [comment]
I have the same problem here IT (Italy)

**Comment by damiano75** [comment]
Any news?
![image](https://user-images.githubusercontent.com/47896789/134375693-9ae088b3-bad5-4b1b-b545-a6a508d48d60.png)

**Comment by magix66** [comment]
same here... Australia

**Comment by 51av0sh** [comment]
Reposting from another open issue so it might help here as well....

So I have the original super old desk fan (DP01) and I've been having issues with the cloud integration since the latest update. I wanted to try local but I'm on hassOS and can't clone the repo and install python (or couldn't figure out how to). I didn't bother with the wifi setup for the local integration since I assumed there was no wifi ssid on this thing since it's so old. Well I was wrong. I was changing the filter today and noticed a sticker inside that can only be seen after removing the filter. Sure enough I saw the ssid and password. Connected flawlessly. If my DP01 has this option then I assume they all do.

**Comment by gfawkes66** [comment]
Same here 'Failed to Connect'

**Comment by w3ihang** [comment]
Same in MY

**Comment by Kakise** [comment]
Honestly there's nothing I can do about it except adding a section in the readme. It has to do with how the Dyson API itself works. If someone has a workaround I'll gladly merge it but until then there's not much I can do.
