### ISSUE TITLE
0.16 version broke Air Quality Sensor for Pure link 

### ISSUE THREAD

**Issue by myevit** [shenxn/ha-dyson#73]
rolled back to 0.15 - sensor is working as before.

**Comment by Kakise** [comment]
Can I have the precise model of your air purifier please ?

0.16 was meant specifically to render the sensors up to date with the latest specification so new sensors were added. Could you try updating to 0.16 and updating the entity list ?

**Comment by myevit** [comment]
TP02 Pure Cool Tower Air Purifier and Fan. In integration it setup as model 475
0.16.1
![image](https://user-images.githubusercontent.com/13375246/143075177-49789836-4349-4456-90c2-7dfaadb091d6.png)

0.15
![image](https://user-images.githubusercontent.com/13375246/143075573-ade3b9ad-77b3-4ada-85ce-085a5d4d828e.png)

**Comment by Kakise** [comment]
Ah yes, so the air quality monitor was purposefully removed in 0.16 because it is deprecated and will be removed from home assistant in a future update. It has been replaced by the particulates and VOC sensors. Your entity list did update correctly, I suggest you just remove the now deleted Air Quality entity.
